### ISSUE TITLE
Update always claims there's a new manifest URL.

### ISSUE THREAD

**Issue by VestOfHolding** [Meneltamar/fvtt-pf2e-magaambya-study-helper#4]
Every time I update all my modules, I get this pop-up:
![image](https://github.com/Meneltamar/fvtt-pf2e-magaambya-study-helper/assets/4349490/64410170-f0d8-4252-815f-7b89e4e36b1e)

Please fix the manifest so this doesn't pop up every single time. Thank you.

**Comment by Meneltamar** [comment]
Fixed.
